# @copyright Wang Zhou 2018. All Rights Reserved.
service: interview-service

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
    name: aws
    runtime: nodejs6.10
    profile: mubaba
    stage: dev
    region: ap-southeast-2

# Permissions
iamRoleStatements:
    - Effect: 'Allow'
      Action:
          - 'dynamodb:*'
      Resource: '*'
    - Effect: 'Allow'
      Action:
          - 's3:PutObject'
      Resource: '*'

package:
    include:
        - node_modules/**
    exclude:
        - node_modules/aws-sdk

functions:
    addExpense:
        name: api-hometrack-${self:provider.stage}
        handler: hometrack/handler.main
        description: Home track exercise, simple no sql sample
        events:
            - http:
                  path: hometrack/sample
                  method: post
                  cors: true
                  